# Generated by Django 4.0.3 on 2022-03-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAutentificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
