# Generated by Django 4.0.3 on 2022-03-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAutentificacion', '0002_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_lastname',
            field=models.TextField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_name',
            field=models.TextField(default='pendiente', max_length=20),
        ),
    ]
